<?php

/**
 * Built-in Bootstrap Icons for admin picks (class must stay in sync with CDN version).
 *
 * @return array<int, array{class: string, label: string}>
 */
return [
    ['class' => 'bi bi-boxes', 'label' => 'Buildings'],
    ['class' => 'bi bi-house-door', 'label' => 'House'],
    ['class' => 'bi bi-house', 'label' => 'Home'],
    ['class' => 'bi bi-building', 'label' => 'Building'],
    ['class' => 'bi bi-shop', 'label' => 'Shop'],
    ['class' => 'bi bi-shop-window', 'label' => 'Shop window'],
    ['class' => 'bi bi-briefcase', 'label' => 'Office'],
    ['class' => 'bi bi-aspect-ratio', 'label' => 'Tower'],
    ['class' => 'bi bi-tree', 'label' => 'Land'],
    ['class' => 'bi bi-geo-alt', 'label' => 'Location'],
    ['class' => 'bi bi-pin-map', 'label' => 'Pin map'],
    ['class' => 'bi bi-map', 'label' => 'Map'],
    ['class' => 'bi bi-water', 'label' => 'Waterfront'],
    ['class' => 'bi bi-wrench-adjustable', 'label' => 'Industrial'],
    ['class' => 'bi bi-hammer', 'label' => 'Construction'],
    ['class' => 'bi bi-grid-3x3-gap', 'label' => 'Grid'],
    ['class' => 'bi bi-pentagon', 'label' => 'Plot'],
    ['class' => 'bi bi-door-open', 'label' => 'Door'],
    ['class' => 'bi bi-key', 'label' => 'Key'],
    ['class' => 'bi bi-calendar-week', 'label' => 'Rent'],
    ['class' => 'bi bi-currency-dollar', 'label' => 'Sale'],
    ['class' => 'bi bi-tags', 'label' => 'Tags'],
    ['class' => 'bi bi-star', 'label' => 'Featured'],
    ['class' => 'bi bi-layers', 'label' => 'Layers'],
    ['class' => 'bi bi-box-seam', 'label' => 'Warehouse'],
    ['class' => 'bi bi-truck', 'label' => 'Logistics'],
    ['class' => 'bi bi-hospital', 'label' => 'Medical'],
    ['class' => 'bi bi-mortarboard', 'label' => 'Education'],
    ['class' => 'bi bi-cup-hot', 'label' => 'Hospitality'],
    ['class' => 'bi bi-p-circle', 'label' => 'Parking'],
    ['class' => 'bi bi-tree-fill', 'label' => 'Garden'],
    ['class' => 'bi bi-sun', 'label' => 'Summer'],
    ['class' => 'bi bi-snow', 'label' => 'Ski'],
    ['class' => 'bi bi-tsunami', 'label' => 'Coastal'],
    ['class' => 'bi bi-wifi', 'label' => 'Smart'],
    ['class' => 'bi bi-shield-check', 'label' => 'Secure'],
    // Filled variants (Bootstrap Icons 1.9.0)
    ['class' => 'bi bi-house-fill', 'label' => 'Home (filled)'],
    ['class' => 'bi bi-house-door-fill', 'label' => 'House (filled)'],
    ['class' => 'bi bi-house-heart', 'label' => 'Dream home'],
    ['class' => 'bi bi-house-heart-fill', 'label' => 'Dream home (filled)'],
    ['class' => 'bi bi-bank', 'label' => 'Bank'],
    ['class' => 'bi bi-bank2', 'label' => 'Bank branch'],
    // Land, plot & floor plan
    ['class' => 'bi bi-pentagon-fill', 'label' => 'Plot (filled)'],
    ['class' => 'bi bi-bounding-box', 'label' => 'Lot size'],
    ['class' => 'bi bi-rulers', 'label' => 'Dimensions'],
    ['class' => 'bi bi-person-bounding-box', 'label' => 'Unit size'],
    ['class' => 'bi bi-bounding-box-circles', 'label' => 'Radius'],
    ['class' => 'bi bi-layout-split', 'label' => 'Floor plan'],
    ['class' => 'bi bi-layout-three-columns', 'label' => 'Multi-unit'],
    ['class' => 'bi bi-columns-gap', 'label' => 'Columns'],
    ['class' => 'bi bi-border-all', 'label' => 'Parcel'],
    ['class' => 'bi bi-square', 'label' => 'Square'],
    ['class' => 'bi bi-square-half', 'label' => 'Half plot'],
    // Location & navigation
    ['class' => 'bi bi-geo-alt-fill', 'label' => 'Location (filled)'],
    ['class' => 'bi bi-pin-map-fill', 'label' => 'Pin map (filled)'],
    ['class' => 'bi bi-map-fill', 'label' => 'Map (filled)'],
    ['class' => 'bi bi-compass', 'label' => 'Compass'],
    ['class' => 'bi bi-compass-fill', 'label' => 'Compass (filled)'],
    ['class' => 'bi bi-signpost', 'label' => 'Signpost'],
    ['class' => 'bi bi-signpost-2', 'label' => 'Signpost 2'],
    ['class' => 'bi bi-globe', 'label' => 'International'],
    ['class' => 'bi bi-globe2', 'label' => 'Global'],
    ['class' => 'bi bi-bullseye', 'label' => 'Pinpoint'],
    ['class' => 'bi bi-geo-fill', 'label' => 'Region'],
    ['class' => 'bi bi-signpost-split', 'label' => 'Crossroads'],
    // Outdoor, views & climate
    ['class' => 'bi bi-flower1', 'label' => 'Landscaped'],
    ['class' => 'bi bi-flower2', 'label' => 'Garden flowers'],
    ['class' => 'bi bi-flower3', 'label' => 'Park'],
    ['class' => 'bi bi-droplet', 'label' => 'Pool'],
    ['class' => 'bi bi-droplet-fill', 'label' => 'Pool (filled)'],
    ['class' => 'bi bi-moisture', 'label' => 'Humidity'],
    ['class' => 'bi bi-umbrella', 'label' => 'Resort'],
    ['class' => 'bi bi-umbrella-fill', 'label' => 'Resort (filled)'],
    ['class' => 'bi bi-life-preserver', 'label' => 'Beach'],
    ['class' => 'bi bi-binoculars', 'label' => 'View'],
    ['class' => 'bi bi-brightness-high', 'label' => 'Natural light'],
    ['class' => 'bi bi-moon-stars', 'label' => 'Night view'],
    ['class' => 'bi bi-sunrise', 'label' => 'Sunrise view'],
    ['class' => 'bi bi-sunset', 'label' => 'Sunset view'],
    ['class' => 'bi bi-sun-fill', 'label' => 'Sunny'],
    ['class' => 'bi bi-snow2', 'label' => 'Winter'],
    ['class' => 'bi bi-cloud-sun', 'label' => 'Climate'],
    ['class' => 'bi bi-cloud-rain', 'label' => 'Rainy climate'],
    ['class' => 'bi bi-cloud-fog2', 'label' => 'Foggy'],
    ['class' => 'bi bi-wind', 'label' => 'Ventilation'],
    ['class' => 'bi bi-fan', 'label' => 'AC / fan'],
    ['class' => 'bi bi-thermometer-half', 'label' => 'Heating'],
    ['class' => 'bi bi-thermometer-sun', 'label' => 'Warm climate'],
    ['class' => 'bi bi-thermometer-high', 'label' => 'Hot climate'],
    ['class' => 'bi bi-thermometer-low', 'label' => 'Cool climate'],
    // Interior & amenities
    ['class' => 'bi bi-door-closed', 'label' => 'Closed unit'],
    ['class' => 'bi bi-door-closed-fill', 'label' => 'Closed unit (filled)'],
    ['class' => 'bi bi-window', 'label' => 'Window'],
    ['class' => 'bi bi-lamp', 'label' => 'Lighting'],
    ['class' => 'bi bi-lamp-fill', 'label' => 'Lighting (filled)'],
    ['class' => 'bi bi-lightbulb', 'label' => 'Bright'],
    ['class' => 'bi bi-lightbulb-fill', 'label' => 'Bright (filled)'],
    ['class' => 'bi bi-fire', 'label' => 'Fireplace'],
    ['class' => 'bi bi-plug', 'label' => 'Utilities'],
    ['class' => 'bi bi-lightning', 'label' => 'Electric'],
    ['class' => 'bi bi-lightning-charge', 'label' => 'Charging'],
    ['class' => 'bi bi-cpu', 'label' => 'Smart building'],
    ['class' => 'bi bi-router', 'label' => 'Connected'],
    // Commercial & mixed use
    ['class' => 'bi bi-briefcase-fill', 'label' => 'Office (filled)'],
    ['class' => 'bi bi-person-workspace', 'label' => 'Workspace'],
    ['class' => 'bi bi-receipt', 'label' => 'Lease'],
    ['class' => 'bi bi-egg-fried', 'label' => 'Restaurant'],
    ['class' => 'bi bi-cup', 'label' => 'Dining'],
    ['class' => 'bi bi-cup-straw', 'label' => 'Café'],
    ['class' => 'bi bi-cup-hot-fill', 'label' => 'Hospitality (filled)'],
    ['class' => 'bi bi-basket', 'label' => 'Retail'],
    ['class' => 'bi bi-cart', 'label' => 'Shopping'],
    ['class' => 'bi bi-megaphone', 'label' => 'Marketing'],
    ['class' => 'bi bi-broadcast', 'label' => 'Studio'],
    ['class' => 'bi bi-easel', 'label' => 'Gallery'],
    ['class' => 'bi bi-hdd-network', 'label' => 'Data center'],
    ['class' => 'bi bi-printer', 'label' => 'Business center'],
    // Finance & transactions
    ['class' => 'bi bi-cash-coin', 'label' => 'Cash'],
    ['class' => 'bi bi-cash-stack', 'label' => 'Investment'],
    ['class' => 'bi bi-piggy-bank', 'label' => 'Savings'],
    ['class' => 'bi bi-piggy-bank-fill', 'label' => 'Savings (filled)'],
    ['class' => 'bi bi-graph-up', 'label' => 'Growth'],
    ['class' => 'bi bi-graph-up-arrow', 'label' => 'Appreciation'],
    ['class' => 'bi bi-arrow-left-right', 'label' => 'Exchange'],
    ['class' => 'bi bi-calendar-check', 'label' => 'Booked'],
    ['class' => 'bi bi-calendar-event', 'label' => 'Event space'],
    ['class' => 'bi bi-file-earmark-lock', 'label' => 'Secure deed'],
    ['class' => 'bi bi-journal-text', 'label' => 'Legal / title'],
    ['class' => 'bi bi-file-earmark-text', 'label' => 'Documents'],
    ['class' => 'bi bi-clipboard-check', 'label' => 'Approved'],
    // Transport & access
    ['class' => 'bi bi-p-square-fill', 'label' => 'Parking (filled)'],
    ['class' => 'bi bi-car-front', 'label' => 'Car access'],
    ['class' => 'bi bi-car-front-fill', 'label' => 'Car access (filled)'],
    ['class' => 'bi bi-train-front', 'label' => 'Metro / rail'],
    ['class' => 'bi bi-train-front-fill', 'label' => 'Metro (filled)'],
    ['class' => 'bi bi-train-lightrail-front', 'label' => 'Light rail'],
    ['class' => 'bi bi-train-lightrail-front-fill', 'label' => 'Light rail (filled)'],
    ['class' => 'bi bi-train-freight-front', 'label' => 'Freight rail'],
    ['class' => 'bi bi-airplane', 'label' => 'Airport nearby'],
    ['class' => 'bi bi-airplane-fill', 'label' => 'Airport (filled)'],
    ['class' => 'bi bi-bicycle', 'label' => 'Cycling'],
    ['class' => 'bi bi-minecart', 'label' => 'Industrial zone'],
    // Quality, status & media
    ['class' => 'bi bi-gem', 'label' => 'Luxury'],
    ['class' => 'bi bi-award', 'label' => 'Award'],
    ['class' => 'bi bi-award-fill', 'label' => 'Award (filled)'],
    ['class' => 'bi bi-patch-check', 'label' => 'Verified'],
    ['class' => 'bi bi-patch-check-fill', 'label' => 'Verified (filled)'],
    ['class' => 'bi bi-star-fill', 'label' => 'Featured (filled)'],
    ['class' => 'bi bi-stars', 'label' => 'Premium'],
    ['class' => 'bi bi-heart', 'label' => 'Favorite'],
    ['class' => 'bi bi-heart-fill', 'label' => 'Favorite (filled)'],
    ['class' => 'bi bi-bookmark', 'label' => 'Saved'],
    ['class' => 'bi bi-bookmark-fill', 'label' => 'Saved (filled)'],
    ['class' => 'bi bi-flag', 'label' => 'Flagship'],
    ['class' => 'bi bi-flag-fill', 'label' => 'Flagship (filled)'],
    ['class' => 'bi bi-lock', 'label' => 'Gated'],
    ['class' => 'bi bi-lock-fill', 'label' => 'Gated (filled)'],
    ['class' => 'bi bi-shield-lock', 'label' => 'Protected'],
    ['class' => 'bi bi-people', 'label' => 'Community'],
    ['class' => 'bi bi-people-fill', 'label' => 'Community (filled)'],
    ['class' => 'bi bi-camera-video', 'label' => 'Virtual tour'],
    ['class' => 'bi bi-images', 'label' => 'Gallery'],
    ['class' => 'bi bi-image', 'label' => 'Photo'],
    ['class' => 'bi bi-film', 'label' => 'Video'],
    ['class' => 'bi bi-eye', 'label' => 'Scenic view'],
    ['class' => 'bi bi-arrows-fullscreen', 'label' => 'Spacious'],
    ['class' => 'bi bi-display', 'label' => 'Showroom'],
    ['class' => 'bi bi-tv', 'label' => 'Media room'],
    ['class' => 'bi bi-telephone', 'label' => 'Contact'],
    ['class' => 'bi bi-mailbox', 'label' => 'Mail service'],
    ['class' => 'bi bi-person-badge', 'label' => 'Agent'],
    ['class' => 'bi bi-hand-thumbs-up', 'label' => 'Recommended'],
    ['class' => 'bi bi-check-circle', 'label' => 'Ready'],
    ['class' => 'bi bi-patch-plus', 'label' => 'New listing'],
    ['class' => 'bi bi-box2', 'label' => 'Package deal'],
    // Build & maintenance
    ['class' => 'bi bi-tools', 'label' => 'Renovation'],
    ['class' => 'bi bi-gear', 'label' => 'Managed'],
    ['class' => 'bi bi-gear-fill', 'label' => 'Managed (filled)'],
    ['class' => 'bi bi-cone-striped', 'label' => 'Under construction'],
    ['class' => 'bi bi-palette', 'label' => 'Design'],
    ['class' => 'bi bi-brush', 'label' => 'Interior design'],
    ['class' => 'bi bi-paint-bucket', 'label' => 'Paint / finish'],
    // Accessibility & wellness
    ['class' => 'bi bi-universal-access', 'label' => 'Accessible'],
    ['class' => 'bi bi-universal-access-circle', 'label' => 'Accessible (circle)'],
    ['class' => 'bi bi-badge-wc', 'label' => 'Restroom'],
    ['class' => 'bi bi-badge-wc-fill', 'label' => 'Restroom (filled)'],
    ['class' => 'bi bi-h-circle', 'label' => 'Hospital marker'],
    ['class' => 'bi bi-h-circle-fill', 'label' => 'Hospital marker (filled)'],
    ['class' => 'bi bi-heart-pulse', 'label' => 'Gym / fitness'],
    ['class' => 'bi bi-heart-pulse-fill', 'label' => 'Gym / fitness (filled)'],
    ['class' => 'bi bi-activity', 'label' => 'Activity'],
    ['class' => 'bi bi-lungs', 'label' => 'Fresh air'],
    ['class' => 'bi bi-lungs-fill', 'label' => 'Fresh air (filled)'],
    ['class' => 'bi bi-bandaid', 'label' => 'First aid'],
    ['class' => 'bi bi-bandaid-fill', 'label' => 'First aid (filled)'],
    ['class' => 'bi bi-prescription2', 'label' => 'Pharmacy'],
    ['class' => 'bi bi-capsule', 'label' => 'Medical clinic'],
    ['class' => 'bi bi-hospital-fill', 'label' => 'Medical (filled)'],
    // Rooms, amenities & lifestyle
    ['class' => 'bi bi-ladder', 'label' => 'Stairs / loft'],
    ['class' => 'bi bi-bookshelf', 'label' => 'Library'],
    ['class' => 'bi bi-book', 'label' => 'Study'],
    ['class' => 'bi bi-book-fill', 'label' => 'Study (filled)'],
    ['class' => 'bi bi-emoji-smile', 'label' => 'Kids friendly'],
    ['class' => 'bi bi-emoji-smile-fill', 'label' => 'Kids friendly (filled)'],
    ['class' => 'bi bi-emoji-heart-eyes', 'label' => 'Beautiful'],
    ['class' => 'bi bi-balloon', 'label' => 'Events'],
    ['class' => 'bi bi-balloon-heart', 'label' => 'Celebration'],
    ['class' => 'bi bi-gift', 'label' => 'Gifted unit'],
    ['class' => 'bi bi-gift-fill', 'label' => 'Gifted unit (filled)'],
    ['class' => 'bi bi-controller', 'label' => 'Game room'],
    ['class' => 'bi bi-puzzle', 'label' => 'Play area'],
    ['class' => 'bi bi-music-note', 'label' => 'Music room'],
    ['class' => 'bi bi-music-note-beamed', 'label' => 'Entertainment'],
    ['class' => 'bi bi-headset', 'label' => 'Call center'],
    ['class' => 'bi bi-headset-vr', 'label' => 'VR tour'],
    ['class' => 'bi bi-cast', 'label' => 'Smart TV cast'],
    ['class' => 'bi bi-camera', 'label' => 'CCTV'],
    ['class' => 'bi bi-camera-fill', 'label' => 'CCTV (filled)'],
    ['class' => 'bi bi-camera-reels', 'label' => 'Surveillance'],
    ['class' => 'bi bi-bell', 'label' => 'Doorbell / alert'],
    ['class' => 'bi bi-bell-fill', 'label' => 'Doorbell (filled)'],
    ['class' => 'bi bi-alarm', 'label' => 'Alarm system'],
    ['class' => 'bi bi-alarm-fill', 'label' => 'Alarm system (filled)'],
    ['class' => 'bi bi-safe', 'label' => 'Safe box'],
    ['class' => 'bi bi-safe2', 'label' => 'Vault'],
    ['class' => 'bi bi-safe2-fill', 'label' => 'Vault (filled)'],
    ['class' => 'bi bi-pass', 'label' => 'Access pass'],
    ['class' => 'bi bi-pass-fill', 'label' => 'Access pass (filled)'],
    ['class' => 'bi bi-key-fill', 'label' => 'Key (filled)'],
    ['class' => 'bi bi-door-open-fill', 'label' => 'Entrance'],
    ['class' => 'bi bi-droplet-half', 'label' => 'Spa / jacuzzi'],
    ['class' => 'bi bi-outlet', 'label' => 'Power outlet'],
    ['class' => 'bi bi-lightning-fill', 'label' => 'Electric (filled)'],
    ['class' => 'bi bi-robot', 'label' => 'Automation'],
    ['class' => 'bi bi-smartwatch', 'label' => 'Wearable / IoT'],
    ['class' => 'bi bi-speedometer', 'label' => 'Performance'],
    ['class' => 'bi bi-speedometer2', 'label' => 'High speed'],
    ['class' => 'bi bi-recycle', 'label' => 'Eco / recycling'],
    ['class' => 'bi bi-box2-heart', 'label' => 'Welcome package'],
    ['class' => 'bi bi-box2-heart-fill', 'label' => 'Welcome package (filled)'],
    ['class' => 'bi bi-box-seam-fill', 'label' => 'Storage (filled)'],
    // Transport extras
    ['class' => 'bi bi-truck-front', 'label' => 'Bus / shuttle'],
    ['class' => 'bi bi-truck-front-fill', 'label' => 'Bus / shuttle (filled)'],
    ['class' => 'bi bi-airplane-engines', 'label' => 'Airport access'],
    ['class' => 'bi bi-airplane-engines-fill', 'label' => 'Airport access (filled)'],
    ['class' => 'bi bi-p-circle-fill', 'label' => 'Parking (circle filled)'],
    ['class' => 'bi bi-p-square', 'label' => 'Parking square'],
    ['class' => 'bi bi-sign-stop', 'label' => 'Traffic'],
    ['class' => 'bi bi-sign-stop-lights', 'label' => 'Traffic lights'],
    ['class' => 'bi bi-sign-turn-right', 'label' => 'Directions'],
    ['class' => 'bi bi-sign-yield', 'label' => 'Road access'],
    ['class' => 'bi bi-escape', 'label' => 'Emergency exit'],
    // Climate extras
    ['class' => 'bi bi-brightness-alt-high', 'label' => 'Daylight'],
    ['class' => 'bi bi-brightness-high-fill', 'label' => 'Bright sun'],
    ['class' => 'bi bi-thermometer-snow', 'label' => 'Cold climate'],
    ['class' => 'bi bi-cloud-lightning', 'label' => 'Storm'],
    ['class' => 'bi bi-cloud-drizzle', 'label' => 'Light rain'],
    ['class' => 'bi bi-cloud-snow', 'label' => 'Snowfall'],
    ['class' => 'bi bi-tornado', 'label' => 'Wind storm'],
    ['class' => 'bi bi-moon', 'label' => 'Night'],
    ['class' => 'bi bi-moon-stars-fill', 'label' => 'Night view (filled)'],
    // People, contact & service
    ['class' => 'bi bi-person', 'label' => 'Resident'],
    ['class' => 'bi bi-person-fill', 'label' => 'Resident (filled)'],
    ['class' => 'bi bi-person-check', 'label' => 'Verified resident'],
    ['class' => 'bi bi-person-plus', 'label' => 'New resident'],
    ['class' => 'bi bi-person-lines-fill', 'label' => 'Directory'],
    ['class' => 'bi bi-person-badge-fill', 'label' => 'Agent (filled)'],
    ['class' => 'bi bi-hand-index', 'label' => 'Select / point'],
    ['class' => 'bi bi-telephone-fill', 'label' => 'Phone'],
    ['class' => 'bi bi-phone', 'label' => 'Mobile'],
    ['class' => 'bi bi-phone-fill', 'label' => 'Mobile (filled)'],
    ['class' => 'bi bi-envelope', 'label' => 'Email'],
    ['class' => 'bi bi-envelope-fill', 'label' => 'Email (filled)'],
    ['class' => 'bi bi-chat-dots', 'label' => 'Live chat'],
    ['class' => 'bi bi-chat-dots-fill', 'label' => 'Live chat (filled)'],
    ['class' => 'bi bi-whatsapp', 'label' => 'WhatsApp'],
    ['class' => 'bi bi-telegram', 'label' => 'Telegram'],
    ['class' => 'bi bi-messenger', 'label' => 'Messenger'],
    ['class' => 'bi bi-facebook', 'label' => 'Facebook'],
    ['class' => 'bi bi-instagram', 'label' => 'Instagram'],
    ['class' => 'bi bi-linkedin', 'label' => 'LinkedIn'],
    ['class' => 'bi bi-youtube', 'label' => 'YouTube'],
    // Time, docs & finance extras
    ['class' => 'bi bi-clock', 'label' => 'Hours'],
    ['class' => 'bi bi-clock-fill', 'label' => 'Hours (filled)'],
    ['class' => 'bi bi-clock-history', 'label' => 'History'],
    ['class' => 'bi bi-stopwatch', 'label' => 'Quick move-in'],
    ['class' => 'bi bi-hourglass', 'label' => 'Pending'],
    ['class' => 'bi bi-calendar', 'label' => 'Schedule'],
    ['class' => 'bi bi-calendar-date', 'label' => 'Appointment'],
    ['class' => 'bi bi-wallet2', 'label' => 'Payment'],
    ['class' => 'bi bi-credit-card', 'label' => 'Card payment'],
    ['class' => 'bi bi-cash', 'label' => 'Cash payment'],
    ['class' => 'bi bi-currency-rupee', 'label' => 'Rupee'],
    ['class' => 'bi bi-bag-check', 'label' => 'Purchase ready'],
    ['class' => 'bi bi-cart-check', 'label' => 'Reserved'],
    ['class' => 'bi bi-bar-chart', 'label' => 'Stats'],
    ['class' => 'bi bi-pie-chart', 'label' => 'Share / split'],
    ['class' => 'bi bi-graph-down', 'label' => 'Discount'],
    ['class' => 'bi bi-file-earmark-pdf', 'label' => 'PDF brochure'],
    ['class' => 'bi bi-file-earmark-word', 'label' => 'Word document'],
    ['class' => 'bi bi-file-earmark-excel', 'label' => 'Spreadsheet'],
    ['class' => 'bi bi-kanban', 'label' => 'Project board'],
    ['class' => 'bi bi-list-check', 'label' => 'Checklist'],
    ['class' => 'bi bi-clipboard', 'label' => 'Clipboard'],
    ['class' => 'bi bi-clipboard-data', 'label' => 'Reports'],
    ['class' => 'bi bi-search', 'label' => 'Search'],
    ['class' => 'bi bi-zoom-in', 'label' => 'Zoom'],
    ['class' => 'bi bi-fullscreen', 'label' => 'Fullscreen'],
    ['class' => 'bi bi-arrows-expand', 'label' => 'Expand'],
    ['class' => 'bi bi-arrows-move', 'label' => 'Flexible layout'],
    ['class' => 'bi bi-info-circle', 'label' => 'Info'],
    ['class' => 'bi bi-question-circle', 'label' => 'FAQ'],
    ['class' => 'bi bi-exclamation-triangle', 'label' => 'Important'],
    ['class' => 'bi bi-check2-circle', 'label' => 'Confirmed'],
    ['class' => 'bi bi-plus-circle', 'label' => 'Add-on'],
    ['class' => 'bi bi-check-circle-fill', 'label' => 'Ready (filled)'],
    ['class' => 'bi bi-eye-fill', 'label' => 'Scenic view (filled)'],
    ['class' => 'bi bi-hand-thumbs-up-fill', 'label' => 'Recommended (filled)'],
    // Legacy — not in Bootstrap Icons 1.9 CDN; keep so existing records pass validation
    ['class' => 'bi bi-buildings', 'label' => 'Buildings (legacy)'],
];
