<?php

/**
 * Built-in Bootstrap Icons for admin picks (class must stay in sync with CDN version).
 *
 * @return array<int, array{class: string, label: string}>
 */
return [
    ['class' => 'bi bi-boxes', 'label' => 'Buildings'],
    ['class' => 'bi bi-house-door', 'label' => 'House'],
    ['class' => 'bi bi-house', 'label' => 'Home'],
    ['class' => 'bi bi-building', 'label' => 'Building'],
    ['class' => 'bi bi-shop', 'label' => 'Shop'],
    ['class' => 'bi bi-shop-window', 'label' => 'Shop window'],
    ['class' => 'bi bi-briefcase', 'label' => 'Office'],
    ['class' => 'bi bi-aspect-ratio', 'label' => 'Tower'],
    ['class' => 'bi bi-tree', 'label' => 'Land'],
    ['class' => 'bi bi-geo-alt', 'label' => 'Location'],
    ['class' => 'bi bi-pin-map', 'label' => 'Pin map'],
    ['class' => 'bi bi-map', 'label' => 'Map'],
    ['class' => 'bi bi-water', 'label' => 'Waterfront'],
    ['class' => 'bi bi-wrench-adjustable', 'label' => 'Industrial'],
    ['class' => 'bi bi-hammer', 'label' => 'Construction'],
    ['class' => 'bi bi-grid-3x3-gap', 'label' => 'Grid'],
    ['class' => 'bi bi-pentagon', 'label' => 'Plot'],
    ['class' => 'bi bi-door-open', 'label' => 'Door'],
    ['class' => 'bi bi-key', 'label' => 'Key'],
    ['class' => 'bi bi-calendar-week', 'label' => 'Rent'],
    ['class' => 'bi bi-currency-dollar', 'label' => 'Sale'],
    ['class' => 'bi bi-tags', 'label' => 'Tags'],
    ['class' => 'bi bi-star', 'label' => 'Featured'],
    ['class' => 'bi bi-layers', 'label' => 'Layers'],
    ['class' => 'bi bi-box-seam', 'label' => 'Warehouse'],
    ['class' => 'bi bi-truck', 'label' => 'Logistics'],
    ['class' => 'bi bi-hospital', 'label' => 'Medical'],
    ['class' => 'bi bi-mortarboard', 'label' => 'Education'],
    ['class' => 'bi bi-cup-hot', 'label' => 'Hospitality'],
    ['class' => 'bi bi-p-circle', 'label' => 'Parking'],
    ['class' => 'bi bi-tree-fill', 'label' => 'Garden'],
    ['class' => 'bi bi-sun', 'label' => 'Summer'],
    ['class' => 'bi bi-snow', 'label' => 'Ski'],
    ['class' => 'bi bi-tsunami', 'label' => 'Coastal'],
    ['class' => 'bi bi-wifi', 'label' => 'Smart'],
    ['class' => 'bi bi-shield-check', 'label' => 'Secure'],
    // Filled variants (Bootstrap Icons 1.9.0)
    ['class' => 'bi bi-house-fill', 'label' => 'Home (filled)'],
    ['class' => 'bi bi-house-door-fill', 'label' => 'House (filled)'],
    ['class' => 'bi bi-house-heart', 'label' => 'Dream home'],
    ['class' => 'bi bi-house-heart-fill', 'label' => 'Dream home (filled)'],
    ['class' => 'bi bi-bank', 'label' => 'Bank'],
    ['class' => 'bi bi-bank2', 'label' => 'Bank branch'],
    // Land, plot & floor plan
    ['class' => 'bi bi-pentagon-fill', 'label' => 'Plot (filled)'],
    ['class' => 'bi bi-bounding-box', 'label' => 'Lot size'],
    ['class' => 'bi bi-rulers', 'label' => 'Dimensions'],
    ['class' => 'bi bi-person-bounding-box', 'label' => 'Unit size'],
    ['class' => 'bi bi-bounding-box-circles', 'label' => 'Radius'],
    ['class' => 'bi bi-layout-split', 'label' => 'Floor plan'],
    ['class' => 'bi bi-layout-three-columns', 'label' => 'Multi-unit'],
    ['class' => 'bi bi-columns-gap', 'label' => 'Columns'],
    ['class' => 'bi bi-border-all', 'label' => 'Parcel'],
    ['class' => 'bi bi-square', 'label' => 'Square'],
    ['class' => 'bi bi-square-half', 'label' => 'Half plot'],
    // Location & navigation
    ['class' => 'bi bi-geo-alt-fill', 'label' => 'Location (filled)'],
    ['class' => 'bi bi-pin-map-fill', 'label' => 'Pin map (filled)'],
    ['class' => 'bi bi-map-fill', 'label' => 'Map (filled)'],
    ['class' => 'bi bi-compass', 'label' => 'Compass'],
    ['class' => 'bi bi-compass-fill', 'label' => 'Compass (filled)'],
    ['class' => 'bi bi-signpost', 'label' => 'Signpost'],
    ['class' => 'bi bi-signpost-2', 'label' => 'Signpost 2'],
    ['class' => 'bi bi-globe', 'label' => 'International'],
    ['class' => 'bi bi-globe2', 'label' => 'Global'],
    ['class' => 'bi bi-bullseye', 'label' => 'Pinpoint'],
    ['class' => 'bi bi-geo-fill', 'label' => 'Region'],
    ['class' => 'bi bi-signpost-split', 'label' => 'Crossroads'],
    // Outdoor, views & climate
    ['class' => 'bi bi-flower1', 'label' => 'Landscaped'],
    ['class' => 'bi bi-flower2', 'label' => 'Garden flowers'],
    ['class' => 'bi bi-flower3', 'label' => 'Park'],
    ['class' => 'bi bi-droplet', 'label' => 'Pool'],
    ['class' => 'bi bi-droplet-fill', 'label' => 'Pool (filled)'],
    ['class' => 'bi bi-moisture', 'label' => 'Humidity'],
    ['class' => 'bi bi-umbrella', 'label' => 'Resort'],
    ['class' => 'bi bi-umbrella-fill', 'label' => 'Resort (filled)'],
    ['class' => 'bi bi-life-preserver', 'label' => 'Beach'],
    ['class' => 'bi bi-binoculars', 'label' => 'View'],
    ['class' => 'bi bi-brightness-high', 'label' => 'Natural light'],
    ['class' => 'bi bi-moon-stars', 'label' => 'Night view'],
    ['class' => 'bi bi-sunrise', 'label' => 'Sunrise view'],
    ['class' => 'bi bi-sunset', 'label' => 'Sunset view'],
    ['class' => 'bi bi-sun-fill', 'label' => 'Sunny'],
    ['class' => 'bi bi-snow2', 'label' => 'Winter'],
    ['class' => 'bi bi-cloud-sun', 'label' => 'Climate'],
    ['class' => 'bi bi-cloud-rain', 'label' => 'Rainy climate'],
    ['class' => 'bi bi-cloud-fog2', 'label' => 'Foggy'],
    ['class' => 'bi bi-wind', 'label' => 'Ventilation'],
    ['class' => 'bi bi-fan', 'label' => 'AC / fan'],
    ['class' => 'bi bi-thermometer-half', 'label' => 'Heating'],
    ['class' => 'bi bi-thermometer-sun', 'label' => 'Warm climate'],
    ['class' => 'bi bi-thermometer-high', 'label' => 'Hot climate'],
    ['class' => 'bi bi-thermometer-low', 'label' => 'Cool climate'],
    // Interior & amenities
    ['class' => 'bi bi-door-closed', 'label' => 'Closed unit'],
    ['class' => 'bi bi-door-closed-fill', 'label' => 'Closed unit (filled)'],
    ['class' => 'bi bi-window', 'label' => 'Window'],
    ['class' => 'bi bi-lamp', 'label' => 'Lighting'],
    ['class' => 'bi bi-lamp-fill', 'label' => 'Lighting (filled)'],
    ['class' => 'bi bi-lightbulb', 'label' => 'Bright'],
    ['class' => 'bi bi-lightbulb-fill', 'label' => 'Bright (filled)'],
    ['class' => 'bi bi-fire', 'label' => 'Fireplace'],
    ['class' => 'bi bi-plug', 'label' => 'Utilities'],
    ['class' => 'bi bi-lightning', 'label' => 'Electric'],
    ['class' => 'bi bi-lightning-charge', 'label' => 'Charging'],
    ['class' => 'bi bi-cpu', 'label' => 'Smart building'],
    ['class' => 'bi bi-router', 'label' => 'Connected'],
    // Commercial & mixed use
    ['class' => 'bi bi-briefcase-fill', 'label' => 'Office (filled)'],
    ['class' => 'bi bi-person-workspace', 'label' => 'Workspace'],
    ['class' => 'bi bi-receipt', 'label' => 'Lease'],
    ['class' => 'bi bi-egg-fried', 'label' => 'Restaurant'],
    ['class' => 'bi bi-cup', 'label' => 'Dining'],
    ['class' => 'bi bi-cup-straw', 'label' => 'Café'],
    ['class' => 'bi bi-cup-hot-fill', 'label' => 'Hospitality (filled)'],
    ['class' => 'bi bi-basket', 'label' => 'Retail'],
    ['class' => 'bi bi-cart', 'label' => 'Shopping'],
    ['class' => 'bi bi-megaphone', 'label' => 'Marketing'],
    ['class' => 'bi bi-broadcast', 'label' => 'Studio'],
    ['class' => 'bi bi-easel', 'label' => 'Gallery'],
    ['class' => 'bi bi-hdd-network', 'label' => 'Data center'],
    ['class' => 'bi bi-printer', 'label' => 'Business center'],
    // Finance & transactions
    ['class' => 'bi bi-cash-coin', 'label' => 'Cash'],
    ['class' => 'bi bi-cash-stack', 'label' => 'Investment'],
    ['class' => 'bi bi-piggy-bank', 'label' => 'Savings'],
    ['class' => 'bi bi-piggy-bank-fill', 'label' => 'Savings (filled)'],
    ['class' => 'bi bi-graph-up', 'label' => 'Growth'],
    ['class' => 'bi bi-graph-up-arrow', 'label' => 'Appreciation'],
    ['class' => 'bi bi-arrow-left-right', 'label' => 'Exchange'],
    ['class' => 'bi bi-calendar-check', 'label' => 'Booked'],
    ['class' => 'bi bi-calendar-event', 'label' => 'Event space'],
    ['class' => 'bi bi-file-earmark-lock', 'label' => 'Secure deed'],
    ['class' => 'bi bi-journal-text', 'label' => 'Legal / title'],
    ['class' => 'bi bi-file-earmark-text', 'label' => 'Documents'],
    ['class' => 'bi bi-clipboard-check', 'label' => 'Approved'],
    // Transport & access
    ['class' => 'bi bi-p-square-fill', 'label' => 'Parking (filled)'],
    ['class' => 'bi bi-car-front', 'label' => 'Car access'],
    ['class' => 'bi bi-car-front-fill', 'label' => 'Car access (filled)'],
    ['class' => 'bi bi-train-front', 'label' => 'Metro / rail'],
    ['class' => 'bi bi-train-front-fill', 'label' => 'Metro (filled)'],
    ['class' => 'bi bi-train-lightrail-front', 'label' => 'Light rail'],
    ['class' => 'bi bi-train-lightrail-front-fill', 'label' => 'Light rail (filled)'],
    ['class' => 'bi bi-train-freight-front', 'label' => 'Freight rail'],
    ['class' => 'bi bi-airplane', 'label' => 'Airport nearby'],
    ['class' => 'bi bi-airplane-fill', 'label' => 'Airport (filled)'],
    ['class' => 'bi bi-bicycle', 'label' => 'Cycling'],
    ['class' => 'bi bi-minecart', 'label' => 'Industrial zone'],
    // Quality, status & media
    ['class' => 'bi bi-gem', 'label' => 'Luxury'],
    ['class' => 'bi bi-award', 'label' => 'Award'],
    ['class' => 'bi bi-award-fill', 'label' => 'Award (filled)'],
    ['class' => 'bi bi-patch-check', 'label' => 'Verified'],
    ['class' => 'bi bi-patch-check-fill', 'label' => 'Verified (filled)'],
    ['class' => 'bi bi-star-fill', 'label' => 'Featured (filled)'],
    ['class' => 'bi bi-stars', 'label' => 'Premium'],
    ['class' => 'bi bi-heart', 'label' => 'Favorite'],
    ['class' => 'bi bi-heart-fill', 'label' => 'Favorite (filled)'],
    ['class' => 'bi bi-bookmark', 'label' => 'Saved'],
    ['class' => 'bi bi-bookmark-fill', 'label' => 'Saved (filled)'],
    ['class' => 'bi bi-flag', 'label' => 'Flagship'],
    ['class' => 'bi bi-flag-fill', 'label' => 'Flagship (filled)'],
    ['class' => 'bi bi-lock', 'label' => 'Gated'],
    ['class' => 'bi bi-lock-fill', 'label' => 'Gated (filled)'],
    ['class' => 'bi bi-shield-lock', 'label' => 'Protected'],
    ['class' => 'bi bi-people', 'label' => 'Community'],
    ['class' => 'bi bi-people-fill', 'label' => 'Community (filled)'],
    ['class' => 'bi bi-camera-video', 'label' => 'Virtual tour'],
    ['class' => 'bi bi-images', 'label' => 'Gallery'],
    ['class' => 'bi bi-image', 'label' => 'Photo'],
    ['class' => 'bi bi-film', 'label' => 'Video'],
    ['class' => 'bi bi-eye', 'label' => 'Scenic view'],
    ['class' => 'bi bi-arrows-fullscreen', 'label' => 'Spacious'],
    ['class' => 'bi bi-display', 'label' => 'Showroom'],
    ['class' => 'bi bi-tv', 'label' => 'Media room'],
    ['class' => 'bi bi-telephone', 'label' => 'Contact'],
    ['class' => 'bi bi-mailbox', 'label' => 'Mail service'],
    ['class' => 'bi bi-person-badge', 'label' => 'Agent'],
    ['class' => 'bi bi-hand-thumbs-up', 'label' => 'Recommended'],
    ['class' => 'bi bi-check-circle', 'label' => 'Ready'],
    ['class' => 'bi bi-patch-plus', 'label' => 'New listing'],
    ['class' => 'bi bi-box2', 'label' => 'Package deal'],
    // Build & maintenance
    ['class' => 'bi bi-tools', 'label' => 'Renovation'],
    ['class' => 'bi bi-gear', 'label' => 'Managed'],
    ['class' => 'bi bi-gear-fill', 'label' => 'Managed (filled)'],
    ['class' => 'bi bi-cone-striped', 'label' => 'Under construction'],
    ['class' => 'bi bi-palette', 'label' => 'Design'],
    ['class' => 'bi bi-brush', 'label' => 'Interior design'],
    ['class' => 'bi bi-paint-bucket', 'label' => 'Paint / finish'],
    // Legacy — not in Bootstrap Icons 1.9 CDN; keep so existing records pass validation
    ['class' => 'bi bi-buildings', 'label' => 'Buildings (legacy)'],
];
